# Generated by Django 2.2.24 on 2023-02-01 08:38

from django.db import migrations, models


def fill_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.filter(construction_year__gte=2015):
        flat.new_building = True
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.filter(construction_year__gte=2015):
        flat.new_building = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190829_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(null=True, verbose_name='Новостройка'),
        ),
        migrations.RunPython(fill_new_building, move_backward),
    ]
