# Generated by Django 2.2.24 on 2023-02-02 10:31

from django.db import migrations


def create_owners_from_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', "Owner")

    for flat in Flat.objects.exclude(owner=""):
        if not Owner.objects.filter(name=flat.owner).exists():
            owner = Owner.objects.create(name=flat.owner, phone=flat.owners_phonenumber, pure_phone=flat.owner_pure_phone)
            owner.flats.add(flat)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', "Owner")
    Owner.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_owner'),
    ]

    operations = [
        migrations.RunPython(create_owners_from_flats)
    ]
