# Generated by Django 2.2.24 on 2023-02-02 11:05

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20230202_1331'),
    ]

    operations = [
    ]
