# Generated by Django 2.2.24 on 2023-02-02 11:32

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230202_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(blank=True, to='property.Owner', verbose_name='Владельцы'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ФИО'),
        ),
    ]
