# Generated by Django 2.2.24 on 2023-02-02 12:53

from django.db import migrations

def link_owner_in_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', "Owner")
    for flat in Flat.objects.all():
        owners = Owner.objects.filter(name=flat.owner, pure_phone=flat.owner_pure_phone)
        for owner in owners:
            flat.owners.add(owner)
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', "Flat")
    for flat in Flat.objects.all():
        flat.owners.clear()
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20230202_1432'),
    ]

    operations = [
        migrations.RunPython(link_owner_in_flat, reverse_code=move_backward)
    ]
