# Generated by Django 2.2.24 on 2023-02-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230202_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.AlterField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(blank=True, to='property.Owner', verbose_name='Собственники'),
        ),
    ]
